import client from './client'
export const getInventory    = (params)   => client.get('/inventory/items', { params })
export const createItem      = body       => client.post('/inventory/items', body)
export const updateItem      = (id, body) => client.patch(`/inventory/items/${id}`, body)
export const restockItem     = (id, qty, notes)  => client.post(`/inventory/items/${id}/restock`, { quantity_to_add: qty, notes })
export const manualDeduct    = (id, body) => client.post(`/inventory/items/${id}/deduct`, body)
export const deleteItem      = id         => client.delete(`/inventory/items/${id}`)
export const getUsageHistory = (item_id)  => client.get(`/inventory/items/${item_id}/usage`)
export const getUsageSummary = (days)     => client.get('/inventory/usage-history', { params: { days } })
export const getAlerts       = ()         => client.get('/inventory/alerts')
export const getPOs          = ()         => client.get('/inventory/purchase-orders')
export const createPO        = body       => client.post('/inventory/purchase-orders', body)
export const updatePO        = (id, body) => client.patch(`/inventory/purchase-orders/${id}`, body)
export const getSuppliers    = ()         => client.get('/inventory/suppliers')
export const createSupplier  = body       => client.post('/inventory/suppliers', body)
export const updateSupplier  = (id, body) => client.patch(`/inventory/suppliers/${id}`, body)
export const deleteSupplier  = id         => client.delete(`/inventory/suppliers/${id}`)