import client from './client'
export const getOrders          = (params)     => client.get('/orders/', { params })
export const getActiveTables    = ()           => client.get('/orders/active-tables')
export const getTableOrder      = (table)      => client.get(`/orders/table/${table}`)
export const createOrder        = body         => client.post('/orders/', body)
export const addItemsToOrder    = (id, body)   => client.post(`/orders/${id}/add-items`, body)
export const removeOrderItem    = (orderId, itemId) => client.delete(`/orders/${orderId}/items/${itemId}`)
export const getOrder           = id           => client.get(`/orders/${id}`)
export const updateStatus       = (id, status) => client.patch(`/orders/${id}/status`, { status })
export const updateKotStatus    = (id, kotNum, status) => client.patch(`/orders/${id}/kot/${kotNum}/status`, { status })
export const collectPayment     = (id, body)   => client.patch(`/orders/${id}/pay`, body)
export const getDashboardSummary  = ()          => client.get('/orders/summary')
export const collectAllForTable   = (table, body) => client.patch(`/orders/table/${table}/collect-all`, body)